name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  google_fonts: 6.1.0
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.3.2


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true  
  image_path: "assets/icons/iconapp.png"  
  adaptive_icon_background: "#FFFFFF"  
  adaptive_icon_foreground: "assets/icons/iconapp.png"


flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
